--liquibase formatted sql

--changeset hoangtd5:001-create-users-table
CREATE TABLE users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username            VARCHAR(50) UNIQUE,
    email               VARCHAR(100)                            NOT NULL UNIQUE,
    first_name          VARCHAR(100)                            NOT NULL,
    last_name           VARCHAR(100)                            NOT NULL,
    mobile_country_code VARCHAR(10),
    mobile_number       VARCHAR(20),
    avatar_url          VARCHAR(500),
    status              VARCHAR(20)                             NOT NULL,
    is_onboarding       BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at          TIMESTAMP                               NOT NULL,
    updated_at          TIMESTAMP                               NOT NULL,
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT ck_users_status CHECK (status IN ('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED'));

--rollback ALTER TABLE users DROP CONSTRAINT IF EXISTS ck_users_status;
--rollback DROP TABLE IF EXISTS users;

--changeset hoangtd5:001-create-member-info-table
CREATE TABLE member_info
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT                                  NOT NULL UNIQUE,
    policy_number    VARCHAR(50)                             NOT NULL,
    company_id       VARCHAR(50),
    member_number    VARCHAR(50),
    dependent_number VARCHAR(50),
    CONSTRAINT pk_member_info PRIMARY KEY (id)
);

ALTER TABLE member_info
    ADD CONSTRAINT fk_member_info_user FOREIGN KEY (user_id) REFERENCES users (id);

--rollback ALTER TABLE member_info DROP CONSTRAINT IF EXISTS fk_member_info_user;
--rollback DROP TABLE IF EXISTS member_info;

--changeset hoangtd5:001-create-rsa-key-pairs-table
CREATE TABLE rsa_key_pairs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key_id      VARCHAR(100)                            NOT NULL UNIQUE,
    public_key  TEXT                                    NOT NULL,
    private_key TEXT                                    NOT NULL,
    created_at  TIMESTAMP                               NOT NULL,
    expires_at  TIMESTAMP                               NOT NULL,
    is_active   BOOLEAN DEFAULT TRUE                    NOT NULL,
    CONSTRAINT pk_rsa_key_pairs PRIMARY KEY (id)
);

--rollback DROP TABLE IF EXISTS rsa_key_pairs;

--changeset hoangtd5:001-create-indexes
CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_users_status ON users (status);
CREATE INDEX idx_rsa_key_pairs_key_id ON rsa_key_pairs (key_id);
CREATE INDEX idx_rsa_key_pairs_active ON rsa_key_pairs (is_active);

--rollback DROP INDEX IF EXISTS idx_rsa_key_pairs_active;
--rollback DROP INDEX IF EXISTS idx_rsa_key_pairs_key_id;
--rollback DROP INDEX IF EXISTS idx_users_status;
--rollback DROP INDEX IF EXISTS idx_users_username;
--rollback DROP INDEX IF EXISTS idx_users_email;
