input {
  file {
    path => "/logs/application.json"
    codec => json {
      ecs_compatibility => "disabled"
    }
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/application-json.sincedb"
    id => "vetautet-app-json-file"
    type => "application"
    stat_interval => "2 seconds"
  }
}

filter {
  mutate {
    convert => {
      "[http.response.status_code]" => "integer"
      "[event.duration_ms]" => "integer"
    }
  }

  mutate {
    remove_field => [
      "host",
      "path",
      "type",
      "APP_NAME",
      "ROOT_LOG_LEVEL",
      "JSON_EVENT_DATASET",
      "MAX_FILE_SIZE",
      "MAX_HISTORY",
      "TOTAL_SIZE_CAP",
      "CONSOLE_LOG_PATTERN",
      "FILE_LOG_PATTERN",
      "LOG_FILE",
      "JSON_LOG_FILE",
      "tags"
    ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "vetautet-app-%{+YYYY.MM.dd}"
    action => "index"
  }
}
